# Generated by Django 2.2 on 2019-04-21 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_friendship_groupmember_groupmessage_grouprequest_usergroup_usermessage_userprofile_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
