# Generated by Django 2.2 on 2019-04-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_friendship_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.CharField(default='Hi, I am a new User', max_length=100),
        ),
    ]
