# Generated by Django 2.2 on 2019-04-28 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0004_userprofile_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRequest',
            new_name='FriendRequest',
        ),
    ]
